# Generated by Django 5.1.3 on 2025-05-03 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organizationgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizationgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tooluser_org_groups',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='tooluser',
            name='groups_m2m',
            field=models.ManyToManyField(related_name='users', through='app.ToolUserGroup', to='app.organizationgroup'),
        ),
    ]
